Problem 1: Convert the following 1-D array with 12 elements into a 2-D array. The outermost dimension will have 2 arrays, each with 6 elements:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#code
New_arry = arr.reshape(2, 6)
print(New_arry)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Problem 2: Convert the following 1-D array into a 3d Array with 1 X 3 elements

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
#code here
New_arry = arr.reshape(1, 3, -1)
print(New_arry)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


Problem 3: Iterate on the elements of the following 3-D array and add 12 if the number is odd and substract -12 if the number is even and print it.


In [6]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#code here
shape = arr.shape
for N in range(shape[0]):
    for M in range(shape[1]):
        for K in range(shape[2]):
            if arr[N][M][K] % 2 == 0:
                arr[N][M][K] -= 12
            else:
                arr[N][M][K] += 12
print(arr)

[[[ 13 -10  15]
  [ -8  17  -6]]

 [[ 19  -4  21]
  [ -2  23   0]]]


Problem 4 : Join two 2-D arrays along rows (axis=1):

In [7]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])

arr2 = np.array([[5, 6], [7, 8],[70,80],[90,100],[110,120]])

#code here
Result = np.concatenate((arr1, arr2), axis=1)
print(Result)


[[  1   2   5   6]
 [  3   4   7   8]
 [  5   6  70  80]
 [  7   8  90 100]
 [  9  10 110 120]]


Problem 5 : Stack two 2-D Array along columns

In [14]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])

arr2 = np.array([[5, 6], [7, 8],[70,80],[90,100],[110,120]])
#code here
Result = np.column_stack((arr1, arr2))
print(Result)

[[  1   2   5   6]
 [  3   4   7   8]
 [  5   6  70  80]
 [  7   8  90 100]
 [  9  10 110 120]]


Problem 5 : Stack two 2-D Array along depth

In [15]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])

arr2 = np.array([[5, 6], [7, 8],[70,80],[90,100],[110,120]])
#code here
Result = np.dstack((arr1, arr2))
print(Result)

[[[  1   5]
  [  2   6]]

 [[  3   7]
  [  4   8]]

 [[  5  70]
  [  6  80]]

 [[  7  90]
  [  8 100]]

 [[  9 110]
  [ 10 120]]]


Problem 6 : Create a filter array for the 1d array. If the number is even then store True in then filter array else False
And then filter the initial array using the filter array.

In [31]:

import numpy as np

arr = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#code here
filter_array = (arr % 2 == 0)

filtered_array = arr[filter_array]

print("Filter Array (Even Numbers):", filter_array)
print("Filtered Array (Even Numbers):", filtered_array)

Filter Array (Even Numbers): [False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]
Filtered Array (Even Numbers): [42 44 46 48 50  2  4  6  8 10]


Problem 7 : Generate 50 random numbers and store it in numpy array and then apply the same operations in problem 6

In [25]:
from numpy import random

#code here
random_numbers = np.random.randint(10, 110, size=50)

filter_array = (random_numbers % 2 == 0)

filtered_numbers = random_numbers[filter_array]

print("Random Numbers Array:", random_numbers)
print("Filter Array (Even Numbers):", filter_array)
print("Filtered Numbers Array (Even Numbers):", filtered_numbers)


Random Numbers Array: [ 83  81  40  35  11  48  74  93  24  91  15  52  72  90  57  12  29  81
  96  18  21  98  77  97  87  70  86  61  11  94 108  21 102  67  50  90
  29  68 107  41 101  84  40  49  63  20  75  10  85  64]
Filter Array (Even Numbers): [False False  True False False  True  True False  True False False  True
  True  True False  True False False  True  True False  True False False
 False  True  True False False  True  True False  True False  True  True
 False  True False False False  True  True False False  True False  True
 False  True]
Filtered Numbers Array (Even Numbers): [ 40  48  74  24  52  72  90  12  96  18  98  70  86  94 108 102  50  90
  68  84  40  20  10  64]


Problem 8 :  Slice from the index 3 from the end to index 1 from the end


In [37]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4],[5,6],[7,8],[9,10]])
#code here
Sliced_Arr = arr1[-3:-1]

print(Sliced_Arr)

[[5 6]
 [7 8]]


Problem 9 : Return every two other element from index 1 to index 5:

In [46]:
import numpy as np
arr = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [47]:
Sliced_Arr = arr[1:6:2]

print(Sliced_Arr)

[42 44 46]


Problem 10 : Generate a random permutation of elements of following array

In [6]:
import numpy as np
arr = np.array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
#code here
Random_permutation = np.random.permutation(arr)

print(Random_permutation)

[ 5 47 43 45 44 46  9 49 48  4  8 10  7  6 50  3  1 42  2 41]
